FROM mcr.microsoft.com/dotnet/sdk:8.0.403-jammy-amd64 AS dotnet
#FROM mcr.microsoft.com/dotnet/sdk:6.0.413-jammy-amd64 AS dotnet
ENV PROTOC_VERSION=3.11.4

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
        curl \
        awscli \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fSL --output protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip \
    && unzip protoc.zip -d protoc \
    && mv protoc/bin/* /usr/local/bin/ \
    && mv protoc/include/* /usr/local/include/ \
    && rm protoc.zip \
    && protoc --version

ENV PATH="$PATH:/usr/share/dotnet"

COPY s3.sh /opt/s3.sh
COPY build.sh /opt/build.sh

RUN chmod +x /opt/s3.sh
RUN chmod +x /opt/build.sh

CMD ["/opt/s3.sh"]
